name:                emordnilap
version:             0.1.0.0
github:              "githubuser/emordnilap"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/emordnilap2#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- lattices
- megaparsec
- text
- parser-combinators

default-extensions: 
- FlexibleInstances
- LambdaCase
- MultiWayIf 
- OverloadedStrings
- GADTs
- KindSignatures
- ExplicitForAll
- TupleSections
- ScopedTypeVariables
- RecordWildCards
- DeriveFunctor

library:
  source-dirs: src

executables:
  emordnilap-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - emordnilap

tests:
  emordnilap-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - emordnilap
    - HTF
    build-tools:
    - cpphs:cpphs
